version: "3.3"
services:
  
  app:
    build: .
    ports:
       - 8000:8000
    volumes:
        - .:/django
    
    image: app:django
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
    # debends_on:
    #       - db
  db:
    image: postgres
    volumes:
         - ./data/db:/var/lib/postgres/data

    environment:
           - POSTGRES_DB=postgres
           - POSTGRES_USER=postgres
           - POSTGRES_PASSWORD=postgres

    container_name: postgres_db

 
